POST http://localhost:8080/booking/offer_employee
Content-Type: application/json

{"employee_id" :  1, "offer_id" : 1 }

###
POST http://localhost:8080/booking/offer_employee
Content-Type: application/json

{"employee_id" :  1, "offer_id" : 2 }

###
POST http://localhost:8080/booking/offer_employee
Content-Type: application/json

{"employee_id" :  2, "offer_id" : 3 }

###
POST http://localhost:8080/booking/offer_employee
Content-Type: application/json

{"employee_id" :  2, "offer_id" : 4 }

###
POST http://localhost:8080/booking/offer_employee
Content-Type: application/json

{"employee_id" :  2, "offer_id" : 5 }

###
POST http://localhost:8080/booking/offer_employee
Content-Type: application/json

{"employee_id" :  3, "offer_id" : 1 }

###
POST http://localhost:8080/booking/offer_employee
Content-Type: application/json

{"employee_id" :  3, "offer_id" : 2 }

###
POST http://localhost:8080/booking/offer_employee
Content-Type: application/json

{"employee_id" :  4, "offer_id" : 6 }