GET http://localhost:8080/booking/appointment
Accept: application/json

###
GET http://localhost:8080/booking/appointment/1
Accept: application/json

###
GET http://localhost:8080/booking/appointment?clientId=1
Accept: application/json

###
GET http://localhost:8080/booking/appointment?employeeId=1
Accept: application/json