POST http://localhost:8080/booking/appointment
Content-Type: application/json

{
  "date":"05/03/2021", "time":"10:00", "client_id": 1, "employee_id": 1, "offer_id": 1, "company_id": 1
}

###
POST http://localhost:8080/booking/appointment
Content-Type: application/json

{
  "date":"06/03/2021", "time":"15:00", "client_id": 2, "employee_id": 3, "offer_id": 2, "company_id": 2
}

###
POST http://localhost:8080/booking/appointment
Content-Type: application/json

{
  "date":"20/03/2021", "time":"11:00", "client_id": 2, "employee_id": 3, "offer_id": 1, "company_id": 2
}

###
POST http://localhost:8080/booking/appointment
Content-Type: application/json

{
  "date":"09/03/2021", "time":"10:00", "client_id": 1, "employee_id": 1, "offer_id": 2, "company_id": 1
}